# Generated by Django 2.0 on 2017-12-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EqualizeHist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageFile',
            field=models.ImageField(upload_to='./'),
        ),
    ]
