# Generated by Django 2.0 on 2017-12-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EqualizeHist_app', '0002_auto_20171229_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imageName',
            field=models.TextField(default=''),
        ),
    ]
