# Generated by Django 2.0 on 2017-12-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EqualizeHist_app', '0004_histogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='histogram',
            name='histName',
            field=models.TextField(default=''),
        ),
    ]
