# Generated by Django 2.0 on 2017-12-30 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EqualizeHist_app', '0005_histogram_histname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histogram',
            name='image',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='histogram', to='EqualizeHist_app.Image'),
        ),
    ]
