# Generated by Django 2.0 on 2017-12-31 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EqualizeHist_app', '0007_auto_20171231_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqualizedHistogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqHist', models.ImageField(upload_to='')),
                ('eqName', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('histogram', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equalized', to='EqualizeHist_app.Histogram')),
            ],
        ),
        migrations.CreateModel(
            name='EqualizedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqImage', models.ImageField(upload_to='./')),
                ('eqImageName', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equalized_image', to='EqualizeHist_app.Image')),
            ],
        ),
    ]
